### ISSUE TITLE
GTX970M (with Optimus) Crashing on Performance Analysis

### ISSUE THREAD

**Issue by WindyDarian** [CIS565-Fall-2016/Project0-CUDA-Getting-Started#7]
![capture](https://cloud.githubusercontent.com/assets/5029519/18137885/45a48912-6f78-11e6-9cb0-251cab21a46e.JPG)

I am using my laptop, it has a GTX970M, but with infamous Nvidia Optimus. Whenever I hit "Launch" for the performance analysis, The program crashes. (Seems like referencing to a null pointer) I have set "Multi-display/mixed-GPU acceleration" to "Single display performance mode"

Below is the result when running without performance analysis tool:

![screenshot-0](https://cloud.githubusercontent.com/assets/5029519/18138178/75631e74-6f79-11e6-8075-2fa5a618152a.png)

**Comment by WindyDarian** [comment]
Update: it works when I uncheck "OpenGL" in "Trace Settings" and traces CUDA only... Does anyone know how to solve this? Or shall I continue with tracing CUDA only?

**Comment by shrekshao** [comment]
Yeah you should trace CUDA Only. 

In the following CUDA Assignments, what we are doing is implementing the algorithm (say Path tracing) in CUDA. OpenGL is only used to copy the image rendered by CUDA to the screen. As a result, that shouldn't be part of our core rendering algorithm, so we don't need to trace OpenGL.

**Comment by shrekshao** [comment]
I preferred you guys post your future questions to [CIS 565 Google Group](https://groups.google.com/forum/#!forum/cis-565-fall-2016), so that every one can see the questions and answers. And I can head back to play games lol

**Comment by WindyDarian** [comment]
Thanks! Happy playing games!
